### ISSUE TITLE
Final Prototype - Jack Tasks

### ISSUE THREAD

**Issue by CarylHenry** [carylsquad/minimism#24]
Hand cursor missing on some buttons (so it shows that you can click on the buttons)
Make data visualization chart more specific to users’ selection

**Comment by atfinke** [comment]
Since this still isn’t done and I don’t know when you plan to do it by, I’m going to add the following tasks for you so @CarylHenry and I don't have to scramble at the last minute once you finish:

- Validate all tasks are working as expected after final commit (using Chrome).
- Create final branch and validate tasks work as expect there (I disabled branch protections so you don’t need approval)

**Comment by jhwiig** [comment]
Good luck scrambling!
